Clarify USM's free behaviour
KhronosGroup/SYCL-Docs pull request #215
Opened 2022-01-28 15:56 UTC by AidanBeltonS

This PR adds two sentences to the `sycl::free` instruction to clarify that it does not wait to release the memory and if there are any enqueued commands which use it there will be undefined behaviour.

This is useful to users as it shows that they must be aware that commands can execute asynchronously and that unlike buffers the implementation will release the memory regardless of dependencies.

2022-01-28 16:14 UTC, tomdeakin requested changes
I think this change makes sense.
Suggested a minor editorial correction.

2022-01-28 16:14 UTC, tomdeakin commented on adoc/chapters/programming_interface.adoc
> +completed.  If <<command, commands>>, that use this memory, are in-progress or
```suggestion
completed.  If <<command, commands>> that use this memory are in-progress or 
```

2022-01-28 16:47 UTC, tomdeakin approved these changes

2022-01-28 17:32 UTC, gmlueck commented on adoc/chapters/programming_interface.adoc
> +are enqueued they will have undefined behavior.
```suggestion
are enqueued the behavior is undefined.
```

Minor nit, but I think this reads a bit better.

2022-01-28 18:11 UTC, gmlueck approved these changes

2022-01-30 20:36 UTC, AerialMantis approved these changes

2022-02-03 17:19 UTC, fraggamuffin commented
LGTM; Aidan please add yourself as contributor, congratulation on first contribution

2022-02-03 18:25 UTC, merged