Add operator= for the 0-dimensional accessors
KhronosGroup/SYCL-Docs pull request #278
Opened 2022-08-25 22:40 UTC by aelovikov-intel

That enables uses like this:

  q.submit([&](sycl::handler &cgh) {
    sycl::local_accessor<int, 0> A{cgh};
    cgh.single_task<class Kernel>([=] { A = 42; });
  });

This PR also fixes incosistency in the description of "operator
reference" for buffer accessor - it is only available for non-atomic
access-mode as mentioned in some places but not in its synopsis.

2022-08-26 21:20 UTC, gmlueck commented on adoc/chapters/programming_interface.adoc
> +accessor &operator=(const value_type &other) const
I think this needs to return a `const accessor &` because the member function is `const`.

2022-08-29 14:37 UTC, tomdeakin commented
LGTM, except this is adding a new API. Can we do that into SYCL 2020?

2022-08-29 14:43 UTC, gmlueck commented
> LGTM, except this is adding a new API. Can we do that into SYCL 2020?

I would put this in the category of "oversight" rather than "new functionality".  In it's current form, there is no way to write a value into a 0-dimension accessor.  Surely, that was not our intent!

2022-08-29 18:06 UTC, gmlueck commented
> Assume operator+=, etc follows from the operator= returning a reference?

We do not currently define any other operators like this.  I was also wondering about adding other operators while reviewing this, but I was concerned about making this PR too big as a "bug fix" against the spec.  It seems like `operator=` is the minimum you need to use a 0-dimensional accessor.  You can always do operations on the raw `T` value and then assign to the accessor.

If we consider adding `+=`, then we need to consider all the other `op=` operators as well as the non-assigning versions.  And then you need to consider the case when `T` doesn't support mathematical operators like `+`.

2022-08-29 18:20 UTC, tomdeakin approved these changes

2022-08-31 18:14 UTC, keryell requested changes
Coding style and too much constness.

2022-08-31 18:14 UTC, keryell commented on adoc/chapters/programming_interface.adoc
> +const accessor &operator=(const value_type &&other) const
Should we have instead
```suggestion
const accessor& operator=(value_type&& other) const
```
?

2022-08-31 18:14 UTC, keryell commented on adoc/chapters/programming_interface.adoc
> +const accessor &operator=(const value_type &other) const
```suggestion
const accessor& operator=(const value_type& other) const
```

2022-08-31 18:14 UTC, keryell commented on adoc/chapters/programming_interface.adoc
> +const host_accessor &operator=(const value_type &&other) const
```suggestion
const host_accessor& operator=(value_type&& other) const
```
?

2022-08-31 18:14 UTC, keryell commented on adoc/headers/accessorBuffer.h
> +  const accessor &operator=(const value_type &other) const;
```suggestion
  const accessor& operator=(const value_type& other) const;
```

2022-09-08 16:18 UTC, fraggamuffin commented
what to do with the type from +=? so prefer minimal change for now
adding api is ok

2022-09-22 14:44 UTC, keryell approved these changes
Thanks.

2022-09-29 16:14 UTC, keryell requested changes
Almost there!

2022-09-29 16:14 UTC, keryell commented on adoc/chapters/programming_interface.adoc
> +const host_accessor &operator=(const value_type &other) const
```suggestion
const host_accessor& operator=(const value_type& other) const
```

2022-09-29 16:14 UTC, keryell commented on adoc/chapters/programming_interface.adoc
> +const local_accessor &operator=(const value_type &other) const
```suggestion
const local_accessor& operator=(const value_type& other) const
```

2022-09-29 16:14 UTC, keryell commented on adoc/chapters/programming_interface.adoc
> +const local_accessor &operator=(const value_type &&other) const
```suggestion
const local_accessor& operator=(const value_type&& other) const
```

2022-09-29 17:18 UTC, keryell approved these changes
Thanks!

2022-09-29 17:18 UTC, merged