Add static constexpr `dimensions` member to all range/id-like types
KhronosGroup/SYCL-Docs pull request #351
Opened 2023-01-26 11:17 UTC by psalz

Partially addresses #270.

2023-01-26 15:00 UTC, gmlueck commented
If we want to put this into SYCL 2020, we should also update the CTS to check it.

2023-01-26 15:15 UTC, keryell commented
I guess we should bike-shed this. Is this for SYCL Next?

2023-01-26 15:30 UTC, psalz commented
> If we want to put this into SYCL 2020, we should also update the CTS to check it.

That's what the label is for! I will create an issue in the CTS repo if this is merged.

2023-03-16 16:34 UTC, nliber requested changes

2023-03-16 17:38 UTC, gmlueck commented on adoc/headers/item.h
> +  static constexpr int dimensions = Dimensions;
Note, however, that parallel_for offsets are a deprecated feature.  I'm not sure we want to add new APIs for deprecated features.

2023-03-16 18:40 UTC, nliber commented on adoc/headers/item.h
> +  static constexpr int dimensions = Dimensions;
Ah, true.  Will approve as is.

2023-03-16 18:40 UTC, nliber approved these changes

2023-04-04 01:51 UTC, keryell approved these changes
I am just discovering https://en.cppreference.com/w/cpp/types/rank which is not yet customizable anyway...
So, let's go for this and bike-shed in the future with some alternative to match `mdspan` and so, for example exposing a `static constexpr rank()` member function.

2023-04-13 16:11 UTC, fraggamuffin commented
LGTM

2023-04-14 02:57 UTC, merged