Editorial fixes to "vec"
KhronosGroup/SYCL-Docs pull request #503
Opened 2023-11-28 16:06 UTC by gmlueck

Fix a few wording problems I noticed when reviewing #479.

2023-11-28 16:11 UTC, TApplencourt approved these changes

2023-11-30 17:09 UTC, keryell requested changes

2023-11-30 17:09 UTC, keryell commented on adoc/chapters/programming_interface.adoc
> +Construct a new instance of the SYCL [code]#vec# class template with the same template parameters as [code]#v# [code]#vec# with each element of the new SYCL [code]#vec# instance the result of an elem
```suggestion
Construct a new instance of the SYCL [code]#vec# class template with the same template parameters as [code]#v# [code]#vec# with each element of the new SYCL [code]#vec# instance the result of an element-wise bitwise +not+ operation on each element of [code]#v# [code]#vec#.
```
and everywhere

2023-11-30 17:09 UTC, keryell commented on adoc/chapters/programming_interface.adoc
> +Construct a new instance of the SYCL [code]#vec# class template with the same template parameters as [code]#v# [code]#vec# with each element of the new SYCL [code]#vec# instance the result of an elem
Actually `[code]#not#`

2023-11-30 17:10 UTC, tomdeakin commented
With asciidoc fixes, ready to merge with 2 approvals.

2023-11-30 22:14 UTC, keryell approved these changes
Thanks!

2023-12-01 13:05 UTC, merged