Specify copy assignment operator for vec swizzles
KhronosGroup/SYCL-Docs pull request #678
Opened 2024-12-06 19:47 UTC by gmlueck

Even though we specify an assignment operator for
`__writeable_swizzle__` like this:

```
template</*unspecified*/>
const __writeable_swizzle__&
operator=(const __writeable_swizzle__</*unspecified*/>& rhs) const
```

The compiler will not select this operator when the left-hand-side has the same type as the right-hand-side.  (Even though the template constraints would allow such a selection.)  Instead, the compiler will generate the default copy assignment operator and call that.

Since the default copy assignment operator would not be correct (performing a shallow copy), the `__writeable_swizzle__` class must provide a user defined copy assignment operator.

The copy assignment operator for `__const_swizzle__` was already deleted in the "constructors" section.  It seemed better to move this to the "member functions" part of the specification, next to the specification for the copy assignment operator for `__writeable_swizzle__`.

2025-02-06 02:42 UTC, nliber requested changes

2025-02-06 02:42 UTC, nliber commented on adoc/chapters/programming_interface.adoc
> +operator=(const __writeable_swizzle__& rhs) const
Why is this a `const` member function?

2025-02-06 16:11 UTC, nliber commented on adoc/chapters/programming_interface.adoc
> +operator=(const __writeable_swizzle__& rhs) const
It is still logically a non-`const` operation.

There is precedent in C++ for this, such as `ostream_iterator::operator=(const T&)` (as well as some of its other operators).

2025-02-06 17:23 UTC, nliber approved these changes

2025-04-02 15:32 UTC, tomdeakin approved these changes

2025-04-03 16:02 UTC, tomdeakin commented
WG approved to merge.

2025-04-03 16:02 UTC, merged